### ISSUE TITLE
Solar Array Crashes Server

### ISSUE THREAD

**Issue by crazysheep86** [NFINIT-Development/AstroBlock#25]
Every time you break a Solar Array with a pickaxe it instantly crashes the server with the error:

java.lang.ClassCastException: micdoodle8.mods.galacticraft.planets.venus.tile.SolarModuleNetwork cannot be cast to micdoodle8.mods.galacticraft.api.transmission.grid.IElectricityNetwork
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseConductor.getNetwork(TileBaseConductor.java:71)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectricalSource.produce(TileBaseUniversalElectricalSource.java:89)
	at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseUniversalElectricalSource.produce(TileBaseUniversalElectricalSource.java:48)
	at micdoodle8.mods.galacticraft.core.tile.TileEntitySolar.func_73660_a(TileEntitySolar.java:245)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

**Comment by crazysheep86** [comment]
[crash-2019-01-30_23.12.54-server.txt](https://github.com/NFINIT-Development/AstroBlock/files/2814787/crash-2019-01-30_23.12.54-server.txt)

**Comment by knoxhack** [comment]
🤔

**Comment by knoxhack** [comment]
duplicated
