### ISSUE TITLE
Unable to start serrver

### ISSUE THREAD

**Issue by markeith07** [NFINIT-Development/AstroBlock#41]
I've been unable to start the server. Sorry if I'm missing something.

Error as followed:

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/Level
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:94)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.Level
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more

**Comment by knoxhack** [comment]
corrupted download, download it again

**Comment by markeith07** [comment]
Will do

**Comment by markeith07** [comment]
Same issues for both Windows and MineOS. Any other Ideal Thanks

**Comment by banggugyangu** [comment]
Same issue with server 1.1.22

I have downloaded the files multiple times, and the issue persists.  This is also both in windows and MineOS

**Comment by BrandonGamesYT** [comment]
Also having the same issue.
![image](https://user-images.githubusercontent.com/26289988/53721039-d46bec00-3e27-11e9-812a-4887f9c70a19.png)
I've tried the server files starting from 1.1.19 to 1.1.23 and none of them seem to work and i get the same error.

**Comment by Knoxxar** [comment]
did you exec the install.bat?

**Comment by knoxhack** [comment]
fixed in 1.1.26
