### ISSUE TITLE
Crash on load (Ticking block entity)

### ISSUE THREAD

**Issue by scoobz1234** [NFINIT-Development/AstroBlock#80]
Game crashing due to Oxygen Sealer.

Time: 9/10/19 5:32 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.doLayer(ThreadFindSeal.java:681)
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.check(ThreadFindSeal.java:183)
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.<init>(ThreadFindSeal.java:106)
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.<init>(ThreadFindSeal.java:60)
	at micdoodle8.mods.galacticraft.core.fluid.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:69)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_73660_a(TileEntityOxygenSealer.java:200)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.doLayer(ThreadFindSeal.java:681)
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.check(ThreadFindSeal.java:183)
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.<init>(ThreadFindSeal.java:106)
	at micdoodle8.mods.galacticraft.core.fluid.ThreadFindSeal.<init>(ThreadFindSeal.java:60)
	at micdoodle8.mods.galacticraft.core.fluid.OxygenPressureProtocol.updateSealerStatus(OxygenPressureProtocol.java:69)
	at micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer.func_73660_a(TileEntityOxygenSealer.java:200)

-- Block entity being ticked --
Details:
	Name: minecraft:gc air sealer // micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenSealer
	Block type: ID #1365 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer // galacticraftcore:sealer)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-992,229,-1001), Chunk: (at 0,14,7 in -62,-63; contains blocks -992,0,-1008 to -977,255,-993), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
	Actual block type: ID #1365 (tile.sealer // micdoodle8.mods.galacticraft.core.blocks.BlockOxygenSealer // galacticraftcore:sealer)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: First_Go
	All players: 1 total; [GCEntityPlayerMP['scoobz1234'/200, l='First_Go', x=-989.07, y=228.00, z=-1003.00]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 7724460207786055652
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_181, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7520202808 bytes (7171 MB) / 11432099840 bytes (10902 MB) up to 11432099840 bytes (10902 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms11000m -Xmx11000m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 188 mods loaded, 188 mods active

**Comment by Firephoenix363** [comment]
@scoobz1234 
Hey did you solved your problem and if yes could you explain to me how cause I have the same problem.
Thanx's for answering

**Comment by Loggio23** [comment]
@Firephoenix363
The problem with the paint tied up because of the ticking block is because of the fashion of ChickenChunks. I also faced this problem recently, looking for a solution, but never found it, then the funny thing is that I started to remove the mods I used after the last launch of the game. And after deleting that particular mod, everything started to run fine.
